title: "*metrics"
email: test@example.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "//metrics-project.net"
url: "//metrics-project.net"
timezone: Europe/Berlin
permalink: pretty
markdown: kramdown
destination: "metrics-website"
gems:
exclude:
  - npm.log
  - node_modules
  - package.json
  - .editorconfig
  - README.md
  - Gemfile
  - Gemfile.lock
  - metrics-website
